//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int Id { get; set; }
        public Nullable<int> EventoId { get; set; }
        public string Zona { get; set; }
        public Nullable<decimal> Precio1 { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
